Repository TEDxJNEC/tedx-2021, pull requests merged in 2021-02, with the labels that each got.

#73 Loader Component
  public/index.html
  src/common/loader.scss
  src/components/Loader.jsx
  src/layouts/index.jsx
Labels: UI

#101 Title Tags to all pages added + SEO firendlyness
  package.json
  src/pages/about.jsx
  src/pages/committee.jsx
  src/pages/highlights.jsx
  src/pages/login.jsx
  src/pages/registration.jsx
  src/pages/team.jsx
  yarn.lock
Labels: enhancement

#100 Added Codesplitting to the app [see bellow for improvements]
  package.json
  src/layouts/index.jsx
  src/routes/index.js
  yarn.lock
Labels: enhancement

#97 Booking Rellated Auth and bounus functionallities
  .env.example
  .eslintrc.json
  package.json
  src/assets/CollegeAmbassdor.svg
  src/assets/Login.svg
  src/assets/check.svg
  src/assets/google-icon.svg
  src/assets/google_logo.svg
  src/assets/patternMobile.svg
  src/assets/search.svg
  src/assets/ui.svg
  src/common/admin_login.scss
  src/common/ambassdorlogin.scss
  src/common/callback.scss
  src/common/fonts.scss
  src/common/formComponent.scss
  src/common/login.scss
  src/common/main.scss
  src/common/registration.scss
  src/components/AmbassdorLogin.jsx
  src/components/Footer.jsx
  src/components/FormComponent.jsx
  src/components/Login.jsx
  src/components/Navbar.jsx
  src/components/Register.jsx
  src/components/dashboard/AdminLogin.jsx
  src/components/form-fields/selectInput.jsx
  src/components/form-fields/textInput.jsx
  src/components/form-fields/textareaInput.jsx
  src/components/icons/CloseMenu.js
  src/components/icons/Login.js
  src/components/icons/MenuIcon.js
  src/components/icons/index.jsx
  src/constants/api.js
  src/constants/routes.js
  src/layouts/index.jsx
  src/pages/about.jsx
  src/pages/admin/login.jsx
  src/pages/committee.jsx
  src/pages/google/callback.jsx
  src/pages/highlights.jsx
  src/pages/login.jsx
  src/pages/registration.jsx
  src/pages/team.jsx
  src/pages/test.jsx
  src/pages/toc.jsx
  src/routes/index.js
  src/store/reducers/auth.js
  yarn.lock
Labels: Functionality, UI, enhancement

#103 Bump Version Performance + Functional features
  .env.example
  .eslintrc.json
  .gitignore
  package.json
  src/assets/CollegeAmbassdor.svg
  src/assets/Login.svg
  src/assets/check.svg
  src/assets/google-icon.svg
  src/assets/google_logo.svg
  src/assets/patternMobile.svg
  src/assets/search.svg
  src/assets/ui.svg
  src/common/admin_login.scss
  src/common/ambassdorlogin.scss
  src/common/callback.scss
  src/common/fonts.scss
  src/common/formComponent.scss
  src/common/login.scss
  src/common/main.scss
  src/common/registration.scss
  src/components/AmbassdorLogin.jsx
  src/components/Footer.jsx
  src/components/FormComponent.jsx
  src/components/Login.jsx
  src/components/Navbar.jsx
  src/components/Register.jsx
  src/components/dashboard/AdminLogin.jsx
  src/components/form-fields/selectInput.jsx
  src/components/form-fields/textInput.jsx
  src/components/form-fields/textareaInput.jsx
  src/components/icons/CloseMenu.js
  src/components/icons/Login.js
  src/components/icons/MenuIcon.js
  src/components/icons/index.jsx
  src/constants/api.js
  src/constants/routes.js
  src/layouts/index.jsx
  src/pages/about.jsx
  src/pages/admin/login.jsx
  src/pages/committee.jsx
  src/pages/google/callback.jsx
  src/pages/highlights.jsx
  src/pages/login.jsx
  src/pages/registration.jsx
  src/pages/team.jsx
  src/pages/test.jsx
  src/pages/toc.jsx
  src/routes/index.js
  src/store/reducers/auth.js
  yarn.lock
Labels: Functionality, UI, enhancement

#113 Updated Google Button
  src/common/login.scss
  src/components/Login.jsx
Labels: UI

#120 Fixed Team List not showing properly on smaller devices and cutting t…
  src/common/tempteam.scss
Labels: bug

#109 Booking Form Component
  src/assets/payment.svg
  src/common/ambassador-navbar.scss
  src/common/main.scss
  src/common/registration.scss
  src/components/FormComponent.jsx
  src/components/ambassdor/AmbassadorNavbar.jsx
  src/components/form-fields/checkInput.jsx
  src/components/form-fields/textInput.jsx
  src/constants/api.js
  src/constants/routes.js
  src/layouts/ambassador.jsx
  src/pages/ambassador/ambassador-dashboard.jsx
  src/pages/index.jsx
  src/pages/registration.jsx
  src/pages/success-registration.jsx
  src/routes/index.js
  yarn.lock
Labels: Functionality, UI

#125 Referral Link issue solved
  src/pages/ambassador/ambassador-dashboard.jsx
Labels: Functionality

#126 Login Image fixed
  src/components/AmbassdorLogin.jsx
Labels: Functionality

#129 Updated validation on Registration Form
  src/components/FormComponent.jsx
  src/components/Navbar.jsx
Labels: enhancement
