Repository TEDxJNEC/tedx-2021, pull requests merged in 2021-01, with the labels that each got.

#19 Tedxjnec/features/setup/font family
  src/common/fonts.scss
  src/common/main.scss
Labels: Functionality, UI

#20 Added CONSTANTS for routing
  package.json
  src/constants/routes.js
  src/index.js
  src/pages/about.jsx
  src/pages/index.jsx
  src/routes/Readme.md
  src/routes/index.js
  yarn.lock
Labels: Functionality

#27 Tedx/features/page/team
  src/pages/team.jsx
Labels: UI

#26 Removed footer code
  src/common/main.scss
  src/components/footer.jsx
  src/pages/index.jsx
Labels: UI

#43 Tedx/features/component/footer
  src/assets/JNEC.svg
  src/assets/social icons/facebook.svg
  src/common/footer.scss
  src/components/Footer.jsx
  src/components/icons/index.jsx
  src/constants/routes.js
Labels: UI
